### ISSUE TITLE
NullPointerException if Vault token is specified during initialization

### ISSUE THREAD

**Issue by arun-gupta** [BetterCloud/vault-java-driver#87]
Setup Vault as explained at:

https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/config-secrets#vault

Java application deployed as Pod in Kubernetes that reads secrets from Vault is:

https://github.com/arun-gupta/java-app-secrets/blob/master/src/main/java/org/examples/java/App.java

Pod spec is:

```
apiVersion: v1
kind: Pod
metadata:
  name: java-app-secrets
spec:
  containers:
  - name: java-app-secrets
    image: arungupta/java-app-secrets:latest
    env:
      - name: VAULT_ADDR
        value: http://ec2-54-237-223-40.compute-1.amazonaws.com:8200
      - name: VAULT_TOKEN
        value: 4e93b3c6-c459-f166-e7e9-6c48044cfdb6
  restartPolicy: Never
```

`VaultConfig` initialized as shown below works and is able to retrieve the secrets:

```
final VaultConfig config = new VaultConfig()
                .address(System.getenv("VAULT_ADDR"))
                .token(System.getenv("VAULT_TOKEN"))
                .sslConfig(new SslConfig().verify(false).build())
                .build();
```

`VaultConfig` initialized as shown below returns a NPE:

```
final VaultConfig config = new VaultConfig()
                .address(System.getenv("VAULT_ADDR"))
                .sslConfig(new SslConfig().verify(false).build())
                .build();
```

Here is the NPE:

```
Exception in thread "main" com.bettercloud.vault.VaultException: java.lang.NullPointerException
	at com.bettercloud.vault.api.Logical.read(Logical.java:84)
	at org.examples.java.App.main(App.java:26)
Caused by: java.lang.NullPointerException
	at java.net.URLEncoder.encode(URLEncoder.java:204)
	at com.bettercloud.vault.rest.Rest.header(Rest.java:173)
	at com.bettercloud.vault.api.Logical.read(Logical.java:56)
	... 1 more
```
